### ISSUE TITLE
Felica type tag just support Japanese iPhone?

### ISSUE THREAD

**Issue by pantaopt** [treastrain/TRETJapanNFCReader#12]
I am Chinese iOS developer. 
We need to Felica tag, but my iPhone cannot read.
Thank you!

**Comment by treastrain** [comment]
@

**Comment by treastrain** [comment]
@pantaopt

NFC(FeliCa) can be read on iPhones with iOS 13.0 or later that support NFC with reader mode.

What's your iPhone?

**Comment by pantaopt** [comment]
> @pantaopt
> 
> NFC(FeliCa) can be read on iPhones with iOS 13.0 or later that support NFC with reader mode.
> 
> What's your iPhone?

Thank you for your response very much!
My iPhone is iPhone X and it is iOS 13.1.2
I will continue to try it.

**Comment by treastrain** [comment]
@pantaopt

hummm
My iPhone is iPhone X too.
Model: MQAY2J/A A1902
What is the Chinese model number?

**Comment by treastrain** [comment]
@pantaopt

Have you set entitlements?

**Comment by pantaopt** [comment]
> @pantaopt
> 
> Have you set entitlements?

Yes.
![image](https://user-images.githubusercontent.com/12946051/67063154-49621b00-f198-11e9-9129-f142e3abf8d8.png)
And Info.plist:

**Comment by pantaopt** [comment]
> @pantaopt
> 
> Have you set entitlements?

My Chinese model number is MQA62CH/A A1865

**Comment by treastrain** [comment]
@pantaopt

Thanks.
Can you scan cards with this app?
https://apps.apple.com/app/id1480265213

This app, Japan NFC Reader is developed by me and using this library.

**Comment by pantaopt** [comment]
@treastrain

**Comment by treastrain** [comment]
@pantaopt 

OK. No problem.
To scan FeliCa Lite or FeliCa Lite-S card, you need to add the system code 0x88B4 to the entitlements (Japan NFC Reader App does not include it.)

**Comment by pantaopt** [comment]
> 88B4

Thank you so much!
You are right. It need add system code 0x88B4 in info.plist for Felica Lite-S card.
I don't know enough for Japan NFC card.
I think your skills are very strong and you are so nice.
Thank you again for your patience and help me solve my problem!

**Comment by pantaopt** [comment]
@treastrain 
I can close this issue if you have no comments.
