### ISSUE TITLE
Can add a simple example of SwiftUI?

### ISSUE THREAD

**Issue by WingCH** [treastrain/TRETJapanNFCReader#13]
I am learning SwiftUI recently and trying use this library in SwiftUI, Unfortunately, I can't use this library work normally in SwiftUI (UIKit is work perfectly).
Can you add a simple example of SwiftUI, just like UIKit sample in `README.md`
Thanks so much!!!

**Comment by onagat** [comment]
@WingCH, I've added a simple example of SwiftUI. #16 
Hopefully, it would help you!

**Comment by WingCH** [comment]
> @WingCH, I've added a simple example of SwiftUI. #16
> Hopefully, it would help you!

great job, thanks your help

**Comment by onagat** [comment]
Shall we close this issue?
Or do we need more examples?

**Comment by treastrain** [comment]
Thank you for your kindness and support.
