### ISSUE TITLE
ライブラリのローカライズについて About the localization

### ISSUE THREAD

**Issue by NeoDigi** [treastrain/TRETJapanNFCReader#14]
いつもお世話になっております。

下記の部分についてお伺いできればと思います。
https://github.com/treastrain/TRETJapanNFCReader/blob/5a0ebd24a0209f1f9285f14fdffcced5adc704ab/TRETJapanNFCReader/JapanNFCReader.swift#L101

こちらの```bundle: Bundle.current```の部分を削除してみたら正常に動いているようですが、もともとそれが使われた理由について教えていただけますでしょうか。

何卒よろしくお願い致します。

**Comment by treastrain** [comment]
@NeoDigi 

ありがとうございます。 
`NSLocalizedString` は
```swift
func NSLocalizedString(_ key: String, tableName: String? = nil, bundle: Bundle = Bundle.main, value: String = "", comment: String) -> String
```
という定義がありますが、`bundle: Bundle.current` と明示的に `TRETJapanNFCReader/TRETJapanNFCReader/xx.lproj/Localizable.strings` を指定しているもので、`Bundle.current` と `Bundle.main` が同じものを指している場合は `bundle: Bundle.current` を削除しても正常に動作します。

現時点での commit では `Localizable.strings` を書き換えたりなどしなければローカライズの文言を変更できないため、こちらについて別なアプローチで変更できる方法を検討中です。

**Comment by NeoDigi** [comment]
Sorry it took me so long to respond.

What I realized is: 
When using the library from Pod and not adding any other string in Localizable.strings this is what I can see:

![IMG_5978E9EA1F5F-1](https://user-images.githubusercontent.com/6572589/69591903-93f87200-1037-11ea-9f5e-a96019cbe16e.jpeg)

The nfcReaderSessionAlertMessage is not localized
When I add nfcReaderSessionAlertMessage in my own Localizable.strings it does not work.

BUT when I change this line:
https://github.com/treastrain/TRETJapanNFCReader/blob/5a0ebd24a0209f1f9285f14fdffcced5adc704ab/TRETJapanNFCReader/JapanNFCReader.swift#L101

to this:

`return NSLocalizedString(key, comment: "")`

Then I can use my own Localizable.strings and its working

**Comment by treastrain** [comment]
@NeoDigi 

Thank you.
I decided to recognize this as a problem.
I will fix the problem with additional support for other translation files.

**Comment by treastrain** [comment]
@NeoDigi 

I want to one question.
What did you use to install this library?
- Carthage
- CocoaPods
- Manual (cloned commit, etc.)

**Comment by NeoDigi** [comment]
@treastrain I used cocoaPods

I wanted to use swift package manager but it didn't work (I forgot why)

**Comment by NeoDigi** [comment]
Thank you, I could update the library with Swift package manager and the localization are working as expected now, I'm closing this
