### ISSUE TITLE
Whether the scheme supports Chinese bank cards?

### ISSUE THREAD

**Issue by vitasapple** [treastrain/TRETJapanNFCReader#17]
My boss let me to read bank cards by ios13.3 beta 3 version .But I cann't solve it , I  ran your code to scan cards but nothing happen.

**Comment by treastrain** [comment]
@vitasapple

Thanks.
Is the card compliantable with FeliCa(NFC-F)?
and does it work on non-beta iOS?

**Comment by vitasapple** [comment]
@treastrain 
I don't know whether it's compatible with  FeliCa, because I don't know what kind of type about my cards , what I know is one of the card【ICBC(Industrial and Commercial Bank of China)】 is obey ISO7816 protocol.

**Comment by vitasapple** [comment]
@treastrain 
sorry to send twice reply 
The code didn't worked on non-beta ios

**Comment by treastrain** [comment]
@vitasapple 

OK. Have you made all the necessary settings to read the tag?
- Include the Near Field Communication Tag Reader Session Formats Entitlement in your app.
- Provide a non-empty string for the NFCReaderUsageDescription key in your app’s info.plist file.
- Add the list of the application identifiers supported in your app to the `com.apple.developer.nfc.readersession.iso7816.select-identifiers` information property list key.
(Source: https://developer.apple.com/documentation/corenfc/nfctagreadersession)

This is the case for my project (Japanese Drivers' Licence Card).
https://github.com/treastrain/TRETJapanNFCReader/blob/20dd8d8e8603bc6ba70e234371b438b65e33c357/Examples/DriversLicenseReader/Info.plist#L65-L72

**Comment by vitasapple** [comment]
@treastrain 
Thanks
- I Open the NFC switch at Capabilities and have MyProjectName. entitlement in my project.
- I also had added NFCReaderUsageDescription in my info.plist 
- My info.plist has identifiers supported as following codes:
```
<key>NFCReaderUsageDescription</key>
	<string>app want to use your phone's nfc</string>
	<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
	<array>
		<string>TAG</string>
	</array>
```
Thank you for your patient guidance, my project can show the scan views but nothing happen whether is bank cards or bus cards or entrance guard card. I don't know the problem is about my card or my codes.
Thanks for your help anyway.

**Comment by treastrain** [comment]
@vitasapple 

I look like you are in the wrong file to write `TAG` in `com.apple.developer.nfc.readersession.iso7816.select-identifiers`.

`TAG` (or `NDEF`) must write in `com.apple.developer.nfc.readersession.formats` in entitlements file.
https://github.com/treastrain/TRETJapanNFCReader/blob/f29eeeaa52ccef530d87860669e3b06f8e334a64/DriversLicenseReader.entitlements#L5-L9

and `com.apple.developer.nfc.readersession.iso7816.select-identifiers` is a list of application identifiers that the app supports in Info.plist.
https://github.com/treastrain/TRETJapanNFCReader/blob/20dd8d8e8603bc6ba70e234371b438b65e33c357/Examples/DriversLicenseReader/Info.plist#L67-L72

**Comment by vitasapple** [comment]
@treastrain 
Thanks for your reply , I fixed the error in the code, and finally scan my card!!!
my entitlements file's code ( as you said ):
```
<key>com.apple.developer.nfc.readersession.formats</key>
<array>
	<string>TAG</string>
<string>NDEF</string>
</array>
```
but some different in info.plist, once I change com.apple.developer.nfc.readersession.iso7816.select-identifiers' value like you said *A0000002310100000000000000000000, A0000002310200000000000000000000, A0000002480300000000000000000000* that I can't scan success my card. so I change my info.plist like this :
```
<key>com.apple.developer.nfc.readersession.formats</key>
<array>
	<string>TAG</string>
<string>NDEF</string>
</array>
```
it is worked , and I find my card's type is MiFare, "<NFCMiFareTag: 0x2837e4390>"
But I still have problem after scan cards , I must write something to my cards so that I can get card's infomations. But I can't even get anything useful , my code is following:
```
- (void)tagReaderSession:(NFCTagReaderSession *)session didDetectTags:(NSArray<__kindof id<NFCTag>> *)tags{
    NSLog(@"%@\n",tags);// print "<NFCMiFareTag: 0x2837e4390>"
    self.curentTag = [tags firstObject];
    if (self.curentTag.type == NFCTagTypeMiFare) {
        id<NFCMiFareTag> mifareTag = [self.curentTag asNFCMiFareTag];
        NSData *data = mifareTag.identifier;
        NSString * dataStr = [NSString stringWithUTF8String:[data bytes]];
        NSLog(@"data:%@，dataStr:%@",data,dataStr);
        //print "data:{length = 4, bytes = 0xed3c71d9}，dataStr:(null)"
    }else{
        NSLog(@"no belong NFCTagTypeMiFare");
    }
}
```
I think "data:{length = 4, bytes = 0xed3c71d9}，dataStr:(null)" is useless, then I tried to writed something to card like this ：
```
[session connectToTag:self.curentTag completionHandler:^(NSError * _Nullable error) {
            if (error) {
                NSLog(@"connect fail :%@",error);
                return ;
            }
//the parameter data is "data:{length = 4, bytes = 0xed3c71d9}，dataStr:(null)" 's data, I know it's wrong , but I don't know what should I write
            [mifareTag sendMiFareCommand:data completionHandler:^(NSData * _Nonnull response, NSError * _Nullable error) {
                NSString * str  =[[NSString alloc] initWithData:response encoding:NSUTF8StringEncoding];
                NSLog(@"response：%@，%@,%@",response,str,error);
//print "response：{length = 0, bytes = 0x}，,Error Domain=NFCError Code=100 "Tag connection lost" UserInfo={NSLocalizedDescription=Tag connection lost}"
            }];
}];
```

**Comment by treastrain** [comment]
@vitasapple 

It was nice that the comment of the entitlements file is correct.

I mentioned `A0000002310100000000000000000000`, `A0000002310200000000000000000000`, `A0000002480300000000000000000000` is the AID of the Japanese Drivers' License Card (compliantable with NFC-B), and these values ​​need to be changed to the AID of each tag(card).

I think `com.apple.developer.nfc.readersession.formats` will NOT have any effect on Info.plist...

I have some knowledge about FeliCa (NFC-F) and NFC-B, but I don't understand MiFare (NFC-A) because I don't have a real MiFare tag or card.

However, if we look at the `protocol NFCMiFareTag` overview [in Apple Developer Documentation](https://developer.apple.com/documentation/corenfc/nfcmifaretag), you can access that card (ICBC card?) by specifying the card's AID in `com.apple.developer.nfc.readersession.iso7816.select-identifiers`.

I guess I need to receive it as `protocol NFCISO7816Tag` instead of NFCMiFareTag. This is my expectation.

**Comment by vitasapple** [comment]
@treastrain 
Hello, yesterday I went to pick up my mother-in-law from hospital and drove 600 kilometers.
today I tried use ISO7816 to receive data from method "didDetectTags" like this:
```
        id<NFCISO7816Tag> mifareTag = [self.curentTag asNFCISO7816Tag];
        NSData *data = mifareTag.identifier;
        NSLog(@"%@",mifareTag.initialSelectedAID);//print null
        NSLog(@"data:%@，dataBety:%@",[data bytes],[data bytes]);//crash here
```
I readed Apple document , it said add "D2760000850101" to com.apple.developer.nfc.readersession.iso7816.select-identifiers like this : 
```
        <key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
	<array>
		<string>TAG</string>
                <string>NDEF</string>
                <string>D2760000850101<string>
	</array>
```
but Xcode throw a mistake : **unable to read property list from file: /Users/jinniu/Desktop/NFCdemo/BusinessTreasure/Info.plist: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 1.) (in target 'BusinessTreasure' from project 'BusinessTreasure')**
Maybe I made some mistake somewhere. How can I get the aid or something useful from the card?

**Comment by treastrain** [comment]
@vitasapple 

The reason for the Xcode error is that the last String tag in your `com.apple.developer.nfc.readersession.iso7816.select-identifiers` array is not closed.

I don't know how to get the MiFare AID from the card...
When I searched for "MiFare aid list" on Google and Baidu, I found several Web pages about AID lists. I cannot guarantee that the information is reliable.

**Comment by treastrain** [comment]
The AID of a Japanese Driver's License that I gave as an example is written in a specification published by the ministry that issued the license.

**Comment by vitasapple** [comment]
@treastrain 
Thank you for your help. Thanks for taking up so much of your time . Best regard
