### ISSUE TITLE
利用iPhoneの機体による問題

### ISSUE THREAD

**Issue by kakukasan** [treastrain/TRETJapanNFCReader#18]
こんにちは

本コードをクローンして幾つかのiPhoneで試したところ、運転免許証の読み込みで問題があったので共有しておきます

- 利用端末： iPhone7 sim free
- 発生問題： 運転免許証ver7、8において読み取りができなかった
  - iPhone Xにて同じ免許証を同様のコードにて実装したところ問題なく読み込むことができました
- 問題発生個所： `func tagReaderSession(_ session: NFCTagReaderSession, didDetect tags: [NFCTag])`
  - `session.connect`にてエラーが発生し読み込みが止まってしまっている

詳しくは調査しきれていませんが、端末に関する問題もあるかもしれません。
また何かありましたら共有させていただきます

**Comment by treastrain** [comment]
@kakukasan 

ありがとうございます。
本ライブラリを用いた iOS App、[Japan NFC Reader](https://apps.apple.com/jp/app/id1480265213) では FeliCa の読み取りに際して iPhone 7、7 Plus ではカードをあわせる位置がかなりシビアであるという知見が得られています。

もしよろしければ iPhone のモデル番号も共有していただけますか？
例えば私の iPhone 11 Pro の場合は
- iPhone12,3
- MWCC2J/A
- A2215

となっています。

**Comment by kakukasan** [comment]
すみません、レンタルで借りたものなので一日ほど確認に時間を頂戴します

他の情報としては、問題が発生した免許証は埼玉で発行されたものです

**Comment by kakukasan** [comment]
お返事遅くなりすみません

- iPhone7
- MNCJ2J/A
- A1779

になります。
独自で試したところ、一部の日本電子旅券や在留カードでも同様の問題が確認できました

**Comment by treastrain** [comment]
@kakukasan 

情報提供ありがとうございます。
> `session.connect`にてエラーが発生し読み込みが止まってしまっている

この部分について、おそらく以下のコードの部分を指しているかと思われますが
https://github.com/treastrain/TRETJapanNFCReader/blob/51babe4d08626cde730c9222814a93dd79b86d1a/TRETJapanNFCReader/ISO14443/DriversLicense/DriversLicenseReader.swift#L126-L130
こちらの `error`（`NFCReaderError`）の内容について何か情報はございますか。
個人的には `readerTransceiveErrorTagConnectionLost` と推測していますが…。

**Comment by kakukasan** [comment]
はい、`readerTransceiveErrorTagConnectionLost`で相違ありません

自分の方でも確認したところ、スキャンを試した免許証のタグがとても薄いものである
ということが…（読み込みに成功したものははっきり見れるものを確認）
本体と書面、両方に問題を抱えていることも関係するかもしれないです…

**Comment by treastrain** [comment]
@kakukasan 

ありがとうございます。
私の方に届いている [Japan NFC Reader](https://apps.apple.com/jp/app/id1480265213) での読み取り不具合も iPhone 7系の端末固有の問題かな…と推測していますので、おそらく我々サードパーティ開発者ではどうにもならない…と現時点では考えています。
この問題に関してこれ以上の策が考えられない場合は、数日後に Close します。ご報告ありがとうございました。

**Comment by kakukasan** [comment]
@treastrain 

こちらこそ調査してくださいありがとうございます。
iPhone8では行けたので7の搭載している技術の問題…せっかくなら8からでもよかったのに…
ありがとうございます。こちらの方はCloseしていただいて構いません。お手数をおかけしました
