### ISSUE TITLE
ローカライズの実装方法の思案

### ISSUE THREAD

**Issue by onagat** [treastrain/TRETJapanNFCReader#21]
ローカライズの実装方法について、議論させてください☺️
下記の方法で、String を extend すると、美しくローカライズできるように思います。

私がざっと見ただけですが、これを利用すると、現状より綺麗になりますでしょうか？

SwiftUI の美しさを生かせるように、ローカライズも綺麗に、直交性高く実装したいと思いまして。

```swift
extension String {
  var localized: String {
    return NSLocalizedString(self, comment: "")
  }
}
```
https://qiita.com/de_kichi/items/b7b12a03871c3f3bb73f

**Comment by treastrain** [comment]
@onagat 

ありがとうございます。
ここで現在のところの実装を確認します。

https://github.com/treastrain/TRETJapanNFCReader/blob/51babe4d08626cde730c9222814a93dd79b86d1a/TRETJapanNFCReader/Extensions.swift#L11-L16

https://github.com/treastrain/TRETJapanNFCReader/blob/51babe4d08626cde730c9222814a93dd79b86d1a/TRETJapanNFCReader/JapanNFCReader.swift#L101-L103

`Bundle` を拡張し、`NSLocalizedString` の定義である
```swift
func NSLocalizedString(_ key: String, tableName: String? = nil, bundle: Bundle = Bundle.main, value: String = "", comment: String) -> String
```
の第3引数に `Bundle.current` をあてることによってローカライズを行っています。
なぜここで `String` のみの拡張とせず、`Bundle` を拡張しているかと申しますと、運転免許証の読み取りの際に運転免許証内に記録されている文字列の文字コード、JIS X 0208 を Unicode に変換する際に [`TRETJapanNFCReader/ISO14443/DriversLicense/JIS0208.TXT`](https://github.com/treastrain/TRETJapanNFCReader/blob/master/TRETJapanNFCReader/ISO14443/DriversLicense/JIS0208.TXT) を使用するのですが、この txt ファイルを取得するために `Bundle.current` を用いています。

https://github.com/treastrain/TRETJapanNFCReader/blob/51babe4d08626cde730c9222814a93dd79b86d1a/TRETJapanNFCReader/ISO14443/DriversLicense/DriversLicenseExtensions.swift#L14

現在のコミットまででは以上の2点で `Bundle.current` を使用しており、2つとも同じ Bundle を指す ということがわかりやすいだろうとの判断でこのような実装になっています。

なお、この方法では Swift Package Manager においてローカライズおよび JIS0208.TXT の取得ができません。Swift Package Manager の Issue の方にはこれを解決すべきとのコメントも挙がっています。

リンク先の Qiita 記事の

> `exampleLabel.text = "exampleTextKey".localized`

は十分に導入の価値があると考え、Bundle の指定方法に関する調整が必要だと考えます。

**Comment by onagat** [comment]
@treastrain コメントありがとうございます。

JIS X 0208 -> Unicode ゆえ、Bundle を使われているんですね。
現在の実装の利点、理解しました。お教えくださり、ありがとうございます！

[TRETJapanNFCReader/ISO14443/DriversLicense/JIS0208.TXT](https://github.com/treastrain/TRETJapanNFCReader/blob/master/TRETJapanNFCReader/ISO14443/DriversLicense/JIS0208.TXT) 
の周りでの、ご苦労とても感じました。日本語を扱う際のJIS0208ゆえの大変な労力 笑

私の今の意見では、現状で十分ですが、この情報が一部でも価値があれば、頭の片隅に入れていただいて、いずれ何か活用いただければ幸いです。

Bundle 周りは、まだ私は専門外で、私は直接コードを触り（触れ）ませんので、
現時点では、この議論は完了という形にして頂いて（issue closeして頂いても）結構です🙇‍♂️
