### ISSUE TITLE
Use in Objective-c project

### ISSUE THREAD

**Issue by always-beta** [treastrain/TRETJapanNFCReader#23]
Hi, looks like it's a great library, and I'd like to import it into my project which is written in Objective-c.
I've imported it via pod, but seems no symbols are  accessible from objective-c, am I missing something?

Thanks.

**Comment by treastrain** [comment]
@always-beta 

Thank you for your comment.

I'm sorry and I don't know Objective-C well. But this library doesn't seem to contain the code needed to use it from Objective-C. So, `pod 'TRETJapanNFCReader'`, it is possible to install a pod, but there are problems in calling each protocol and more.

**Comment by always-beta** [comment]
I see, probably I need to mix swift with o-c in my project and calling your library within swift files.
Thanks anyway!
