### ISSUE TITLE
Cannot decode from JIS X 0208 (with Swift Package Manager)

### ISSUE THREAD

**Issue by treastrain** [treastrain/TRETJapanNFCReader#25]
#24 でも議論されていた、Swift Package Manager から本ライブラリを使用すると発生するローカライズについての問題の解決策を探します。

To find solutions to the issue decoding from JIS X 0208 when using this library from Swift Package Manager discussed in #24 .

**Comment by treastrain** [comment]
衝撃的かつ笑撃的なことがわかりました。改めて [JIS0208.TXT](https://github.com/treastrain/TRETJapanNFCReader/blob/a7b6da719c0ea2c3ea2d60f5b45c0d5caa5be207/Sources/MIFARE/DriversLicense/JIS0208.TXT) を確認していたところ、次のような文言がありました。

https://github.com/treastrain/TRETJapanNFCReader/blob/a7b6da719c0ea2c3ea2d60f5b45c0d5caa5be207/Sources/MIFARE/DriversLicense/JIS0208.TXT#L38-L41

JIS X 0208 の bytes に `0x8080` を加算すれば何も不自由なく EUC-JP に変換でき、Swift は標準で `String.Encoding.japaneseEUC` が用意されているため、何も考えることなく String にすることができました。

**どうして気づかなかったのか…………。**
JIS0208.TXT およびそれを用いて変換するコード等は[最新のコミット`0d1aaeb`](https://github.com/treastrain/TRETJapanNFCReader/commit/0d1aaeb7d67b8710800a5112176df692147329e7)で削除しました。

**Comment by Qs-F** [comment]
なんと、Swift EUC-JPならいけたんですね… お疲れ様です…
