### ISSUE TITLE
Octopus card Years

### ISSUE THREAD

**Issue by WingCH** [treastrain/TRETJapanNFCReader#3]
Base on the document about [Octopus](https://github.com/metrodroid/metrodroid/wiki/Octopus)

> cards allow a negative balance of up to 50 HKD (previously 35 HKD). This results in the balance being encoded differently.

How do I know when the card was released by programming?

Thanks to your help!

**Comment by treastrain** [comment]
Octopus カードで我々が読み取れる情報の中に、カードの発行日が含まれていないので、プログラムによって判別することができません…。私もいろいろな情報を探しましたが、これはおそらく確かな情報です。

The data we can read with an Octopus card does not include the card issue date. Therefore, it cannot be determined by the program. I also looked for a variety of information, but it is almost certain.

Thanks @WingCH
