### ISSUE TITLE
English Please

### ISSUE THREAD

**Issue by MrPans** [treastrain/TRETJapanNFCReader#33]
It's an awesome project but people around the world can not read the README written by Japanese.  Please add an English version.

**Comment by treastrain** [comment]
Thanks @MrPans 

As a provisional measure, the English version of the README has been set up on the [`english-for-README` ](https://github.com/treastrain/TRETJapanNFCReader/tree/english-for-README) branch.

Thanks to @Qs-F for his commitment.
