### ISSUE TITLE
Get UID And Serial Number of the NFC Tag iOS

### ISSUE THREAD

**Issue by shamdass** [treastrain/TRETJapanNFCReader#37]
I'm developing an application in which I want to get the NFC serial number and Identifier of a NFC tag. When I press a button, I want the application to find the UID and serial number of the NFC card. The only problem is that I have no idea how to get the UID and and serial number if that's possible on iOS. I m trying to get NFC identifier but i don't know how to get serial number of NFC Tag. 

Code:- 

    class ScanNFCTag: NFCTagReaderSessionDelegate {

    import CoreNFC

    var session: NFCTagReaderSession?

    func scanNFCTag(sender: UIButton!) {
         self.session = NFCTagReaderSession(pollingOption: .iso14443, delegate: self)
         self.session?.alertMessage = "Hold Your Phone Near the NFC Tag"
         self.session?.begin()
    }

    func tagReaderSessionDidBecomeActive(_ session: NFCTagReaderSession) {
        print("Session Begin!")
    }
    
    func tagReaderSession(_ session: NFCTagReaderSession, didInvalidateWithError error: Error) {
        print(error.localizedDescription)
    }
    
    func tagReaderSession(_ session: NFCTagReaderSession, didDetect tags: [NFCTag]) {
        if tags.count > 1{
            session.alertMessage = "More Than One Tag Detected, Please try again"
            session.invalidate()
        }
        
        let tag = tags.first!
        session.connect(to: tag) { (error) in
            if nil != error{
                session.invalidate(errorMessage: error?.localizedDescription ?? "")
            }
            if case let .miFare(sTag) = tag{
                let UID = sTag.identifier.map{ String(format:"%.2hhx", $0)}.joined()
                session.alertMessage = "Successfully linked tag to location"
                session.invalidate()
                DispatchQueue.main.async {
                    print("NFC Identifer = ", "\(UID)")
                   }
               }
           }
       }
    }

Info list:- 

[https://i.stack.imgur.com/XjINx.png](url)

So, Here is the my code please let me know if i m doing wrong please correct me. Can someone please explain to me how to get serial number and UID of NFC tag,

Any help would be greatly appreciated.

Thanks in advance.

**Comment by treastrain** [comment]
@shamdass 

こんにちは。コメントありがとうございます。
まず、iOS で Core NFC を使うために必要な前準備ができているかを確認してください。
https://github.com/treastrain/TRETJapanNFCReader/issues/17#issuecomment-558698885

私の知る限り iOS で NFC に接続するには、接続したい NFC タグの AID をあらかじめ Info.plist に記載する必要があります。

----------

Thank you for your comment.
First, make sure you have the necessary preparations to use Core NFC on iOS. → https://github.com/treastrain/TRETJapanNFCReader/issues/17#issuecomment-558698885

As far as I know, to connect to NFC on iOS, the AID of the NFC tag you want to connect to must be listed in Info.plist in advance.

**Comment by shamdass** [comment]
Yes I already set up all the things, So could you please help me

**Comment by Qs-F** [comment]
@shamdass 
It seems your question is not relevant to this project directly, pls use StackOverflow or others instead.

**Comment by treastrain** [comment]
@shamdass 
I checked your project's info.plist. I think you must add the list of the application identifiers (AID) supported in your app to the `com.apple.developer.nfc.readersession.iso7816.select-identifiers` information property list key.
(Source: https://developer.apple.com/documentation/corenfc/nfctagreadersession) → https://github.com/treastrain/TRETJapanNFCReader/issues/17#issuecomment-558698885

And I would also recommend asking questions in the StackOverflow etc. rather than in this project issue. I'm sorry I couldn't be of any help.
