### ISSUE TITLE
想加中文

### ISSUE THREAD

**Issue by ghost** [treastrain/TRETJapanNFCReader#5]
想加中文

**Comment by onagat** [comment]
@treastrain お教えいただきたいのですが、下記ファイルの中国語相当を作れば良いのでしょうか？

[TRETJapanNFCReader/en.lproj/Localizable.strings](https://github.com/treastrain/TRETJapanNFCReader/blob/master/TRETJapanNFCReader/en.lproj/Localizable.strings)

**Comment by treastrain** [comment]
@onagat 

以前、香港の有志の方に
- 简体中文 (Simplified Chinese) / zh-Hans
- 繁體中文 (Traditional Chinese) / zh-Hant
- 繁體中文（香港） (Traditional Chinese (Hong Kong)) / zh-HK

の翻訳をしていただいたスプレッドシートがあるのですが、私のリソースが回っておらず `xx.lproj/Localizable.strings.strings` ファイル化できていません。
もうしばらくお待ちください…。

**Comment by treastrain** [comment]
@ghost @onagat 

I added Localizable.strings for Simplified Chinese, Traditional Chinese, Simplified Chinese (Hong Kong) to develop branch.
- [TRETJapanNFCReader/zh-Hans.lproj/Localizable.strings](https://github.com/treastrain/TRETJapanNFCReader/blob/develop/TRETJapanNFCReader/zh-Hans.lproj/Localizable.strings)
- [TRETJapanNFCReader/zh-Hant.lproj/Localizable.strings](https://github.com/treastrain/TRETJapanNFCReader/blob/develop/TRETJapanNFCReader/zh-Hant.lproj/Localizable.strings)
- [TRETJapanNFCReader/zh-HK.lproj/Localizable.strings](https://github.com/treastrain/TRETJapanNFCReader/blob/develop/TRETJapanNFCReader/zh-HK.lproj/Localizable.strings)

**Comment by onagat** [comment]
chears!

友達に中国出身者がたくさんいるので、聞いてみました！
プレッシャー与えるつもりはなかったのですが　笑
ありがとうございます😊

**Comment by treastrain** [comment]
Those localizations are included in the 1.0.3 release. #22
