### ISSUE TITLE
Testflight Validate:  NDEF is disallowed

### ISSUE THREAD

**Issue by WingCH** [treastrain/TRETJapanNFCReader#6]
I am trying to upload my app to TestFlight, which using TRETJapanNFCReader library

Error: 
> Invalid entitlement for core nfc framework The sdk version 13.0 and min OS version 13.0 are not compatible for the entitlement 'com. Apple developer nfc. Readersession formats because NDEF is disallowed

<img width="745" alt="Xnip2019-09-27_13-37-36" src="https://user-images.githubusercontent.com/19588517/65744785-08905c80-e12c-11e9-8aec-1e56606cec0a.png">

I have tried  this [solution](https://stackoverflow.com/questions/57530604/xcode-11-beta-cant-upload-app-to-testflight/58128365#58128365), but it cannot completely solved [[reason](https://stackoverflow.com/questions/57530604/xcode-11-beta-cant-upload-app-to-testflight/58128365#58128365)]

Any Solution?
Please!

**Comment by WingCH** [comment]
also in Xcode 11.1(sdk version 13.1)

![image](https://user-images.githubusercontent.com/19588517/65755130-12728980-e145-11e9-82a6-b4b474562ebc.png)

**Comment by treastrain** [comment]
Thanks @WingCH 

"Because NDEF is disallowed."
If your target is set to iOS 13.0 earlier, It is necessary to include NDEF in addition to TAG.

**Comment by WingCH** [comment]
@treastrain Please your reply!
I already choose target iOS 13.1, but also have this error.

Do you have this problem? when you upload apps to target


![image](https://user-images.githubusercontent.com/19588517/65782718-dceb9180-e180-11e9-88d9-d21c2dcb5701.png)

![image](https://user-images.githubusercontent.com/19588517/65782808-0a383f80-e181-11e9-8020-ca6063d10401.png)
![image](https://user-images.githubusercontent.com/19588517/65782843-263be100-e181-11e9-8639-48fb64c5e08d.png)

**Comment by treastrain** [comment]
Thanks @WingCH 

Hmm...
I set TAG and NDEF like this and could upload to App Store Connect.

![スクリーンショット 2019-09-28 18 26 45](https://user-images.githubusercontent.com/13805382/65814537-10c8c480-e21e-11e9-87d3-b34b5393dfba.png)

Is NFC Tag Reading capability for the app enabled in Certificates, Identifiers & Profiles?
https://developer.apple.com/account/resources/identifiers/list

**Comment by WingCH** [comment]
I am already enabled NFC Tag Reading capability in Certificates, Identifiers & Profiles
![image](https://user-images.githubusercontent.com/19588517/65817549-0ff25b80-e23b-11e9-874d-8b3ae7754106.png)

I just remove the `NDEF` once again, but  I don't know why it doesn't affect the nfc function.  
I think this is a bad solution

![image](https://user-images.githubusercontent.com/19588517/65817503-4a0f2d80-e23a-11e9-99c7-ccf2817547ba.png)

Anyway thanks for your help and reply, This library is very great!!!

**Comment by treastrain** [comment]
Sorry for not being able to help. @WingCH
