### ISSUE TITLE
[ QUESTION ] Read basic inforation from MyNumber

### ISSUE THREAD

**Issue by Jageen** [treastrain/TRETJapanNFCReader#73]
It is not an issue but more an question.

How can we read basic information from MyNumber card ?

1. Name
2. Address
3. Date of birth
4. etc

**Comment by treastrain** [comment]
Hello @Jageen . Thank you for your question!

I was unable to prepare the time I allotted for the implementation of that feature, and here is what I have implemented along the way. Perhaps that will be helpful to you. https://github.com/treastrain/TRETJapanNFCReader/commit/dbd6fa555369d28c8a7ff128c2855f283251ca8b

You are welcome to send me additional questions or messages.

**Comment by Jageen** [comment]
Thank you for sharing partial implementation it will help me to kick start process.

Do you have any way I can MOCK, or SANDBOX MyNumber card ? for development and testing purpose ?

**Comment by treastrain** [comment]
@Jageen 

When I am/was developing this, I'm taking a method to read my and my family's Individual Number Cards (マイナンバーカード) as `Data` using Core NFC's API, so that I don't have to re-read the cards every time I do parsing or other tests.
